AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Phonebook Application. This template creates Application Load Balancer 
  with Auto Scaling Group of Amazon Linux 2 (ami-00a205cb8e06c3c4e - Frankfurt) EC2 Instances which host Python Flask Web Application.
  EC2 instances are placed within LimaWebServerSecurityGroup which allows http (80) connections only from LimaALBSecurityGroup,
  and allows tcp(3306) connections only within itself. RDS DB instance is placed within LimaWebServerSecurityGroup so that
  Database Server can communicate with Web Servers.

  Application Load Balancer is placed within LimaALBSecurityGroup which allows http (80) connections from antwhere.
  LimaAutoScalingGroup Auto Scaling Group is using the LimaWebServerLaunchTemplate Launch Template in order to spin up instances needed.
  LimaWebServerLaunchTemplate Launch Template is configured to prepare Python Flask environment on EC2,
  and to deploy Phonebook Application on Flask Server after downloading the app code from my Github repository.
  

Resources:
  LimaWebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP connection only from LimaALBSecurityGroup
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !GetAtt LimaALBSecurityGroup.GroupId
        - IpProtocol: tcp #Test için açıldı. Deneme sonrası kaldırılacak.
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


  LimaALBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enables HTTP connection from everywhere.
      GroupName: String
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0


  LimaWebServerLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateData:
          ImageId: ami-00a205cb8e06c3c4e  #  Region değişikliğinde değiştirilecek...
          InstanceType: t2.micro
          KeyName: 20200824  # değiştirilecek
          SecurityGroupIds: 
            - !GetAtt LimaWebServerSecurityGroup.GroupId
          TagSpecifications: 
            - ResourceType: instance
              Tags: 
                - Key: Name
                  Value: !Sub Web Server of ${AWS::StackName}  #Stack name Stack oluşturulurken veriliyor...
          UserData: 
            Fn::Base64:
              !Sub 
              - |
                #! /bin/bash
                yum update -y
                yum install python3 -y
                pip3 install flask
                pip3 install flask_mysql
                pip3 install flask_sqlalchemy
                echo "${MyDBURI}" > /home/ec2-user/dbserver.endpoint
                FOLDER="https://raw.githubusercontent.com/flovearth/55_PhonebookWebApp_RDSonEC2/main/"
                curl -s --create-dirs -o "/home/ec2-user/templates/index.html" -L "$FOLDER"templates/index.html
                curl -s --create-dirs -o "/home/ec2-user/templates/add-update.html" -L "$FOLDER"templates/add-update.html
                curl -s --create-dirs -o "/home/ec2-user/templates/delete.html" -L "$FOLDER"templates/delete.html
                curl -s --create-dirs -o "/home/ec2-user/app.py" -L "$FOLDER"phonebook-app.py
                python3 /home/ec2-user/app.py
              - MyDBURI: !GetAtt LimaRDSDBInstance.Endpoint.Address                


  LimaTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: instance
      UnhealthyThresholdCount: 3
      HealthyThresholdCount: 2
      VpcId: !GetAtt LimaWebServerSecurityGroup.VpcId  #  LimaWebserverSecurity Group da kullanılabilir mi??
  

  LimaLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt LimaALBSecurityGroup.GroupId
      Subnets:
        - subnet-65af6c19 #Herkes kendi VPC'deki default subnet'ini yazacak
        - subnet-edd80ea1
        - subnet-88d84ce2
      Type: application
  

  LimaListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:  #required
        - TargetGroupArn: !Ref LimaTargetGroup
          Type: forward
      LoadBalancerArn: !Ref LimaLoadBalancer
      Port: 80  #required
      Protocol: HTTP  #required


  LimaAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones:
        !GetAZs ""
      DesiredCapacity: 1
      HealthCheckGracePeriod: 300
      HealthCheckType: ELB
      LaunchTemplate: 
        LaunchTemplateId: !Ref LimaWebServerLaunchTemplate
        Version: !GetAtt LimaWebServerLaunchTemplate.LatestVersionNumber
      MaxSize: 3 
      MinSize: 1 
      TargetGroupARNs: 
        - !Ref LimaTargetGroup


  # LimaRDSSecurityGroup:  # Yeni tanımlanan  FRANKFURT REGION'DAN DOLAYI KULLANILMADI
  #   Type: "AWS::RDS::DBSecurityGroup"
  #   Properties:
  #     GroupDescription: LimaRDSSecurityGroup #required  
  #     DBSecurityGroupIngress: #required
  #       - CIDRIP: 0.0.0.0/0
  #       - EC2SecurityGroupId: !GetAtt LimaWebServerSecurityGroup.GroupId


  LimaRDSDBInstance:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 0
      # DBClusterIdentifier: phonebook # phonebook yazıldı.
      DBInstanceClass: db.t2.micro #required
      DBInstanceIdentifier: floveARThDBinstance
      DBName: phonebook
      # DBSecurityGroups:  # eklendi 21.10 # tekrar çıkarıldı. 23.10
      #   - !Ref LimaRDSSecurityGroup  # eklendi 21.10 # tekrar çıkarıldı. 23.10
      VPCSecurityGroups:  #  RDS security groupp bu region'da olmadığı için değiştirildi.
        - !GetAtt LimaWebServerSecurityGroup.GroupId  #  Sonuna GroupId eklendi.
      DeleteAutomatedBackups: true
      Engine: MySQL
      EngineVersion: 8.0.19
      MasterUserPassword: 1234567890
      MasterUsername: admin
      MultiAZ: false
      Port: 3306
      PubliclyAccessible: true # ???????
  

  
Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${ALBAddress}
      - ALBAddress: !GetAtt LimaLoadBalancer.DNSName
    Description: Phonebook Application Load Balancer URL